version: 3

vars:
  Destination: pazu
  Os: linux
  Arch: amd64

tasks:
  deploy:
    desc: Deploy to {{ .Destination }}
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - for: ["dkimsign", "dkim-verify", "dkim-keygen"]
        cmd: go build -C cmd/{{ .ITEM }} -o {{ .ITEM }}-{{ .Os }}-{{ .Arch }}
      - for: ["dkimsign", "dkim-verify", "dkim-keygen"]
        cmd: rsync -avz cmd/{{ .ITEM }}/{{ .ITEM }}-{{ .Os }}-{{ .Arch }} {{ .Destination }}:{{ .ITEM }}

  release:
    desc: Release to github
    cmds:
      - goreleaser release --clean
